// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApuz1wKLgn-JG2CfnKQSPRkyTHqZMKGBk',
    appId: '1:12578197758:web:43a6c93f4e1eb747ead5af',
    messagingSenderId: '12578197758',
    projectId: 'medicare-118b0',
    authDomain: 'medicare-118b0.firebaseapp.com',
    storageBucket: 'medicare-118b0.firebasestorage.app',
    measurementId: 'G-9FLNPCM3QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BrG-DeEb0jQ1bwxaYyrwOB5NilBBlAc',
    appId: '1:12578197758:android:90820242da11bb17ead5af',
    messagingSenderId: '12578197758',
    projectId: 'medicare-118b0',
    storageBucket: 'medicare-118b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYKbC4Y9Nx2_1whJ6mW2qALLV5dfv7cg',
    appId: '1:12578197758:ios:f137ff3c79773627ead5af',
    messagingSenderId: '12578197758',
    projectId: 'medicare-118b0',
    storageBucket: 'medicare-118b0.firebasestorage.app',
    iosBundleId: 'com.example.kitchenKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYKbC4Y9Nx2_1whJ6mW2qALLV5dfv7cg',
    appId: '1:12578197758:ios:f137ff3c79773627ead5af',
    messagingSenderId: '12578197758',
    projectId: 'medicare-118b0',
    storageBucket: 'medicare-118b0.firebasestorage.app',
    iosBundleId: 'com.example.kitchenKing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApuz1wKLgn-JG2CfnKQSPRkyTHqZMKGBk',
    appId: '1:12578197758:web:7a12d35db659c210ead5af',
    messagingSenderId: '12578197758',
    projectId: 'medicare-118b0',
    authDomain: 'medicare-118b0.firebaseapp.com',
    storageBucket: 'medicare-118b0.firebasestorage.app',
    measurementId: 'G-V3EES2TGX8',
  );
}
